name: Cancel
on:
  push:
    branches:
      - master
      - next
      - main
  pull_request:
    branches:
      - master
      - next
      - main
permissions: {} # none
jobs:
  cancel:
    permissions:
      actions: write
    name: Cancel Previous Runs
    runs-on: ubuntu-22.04
    timeout-minutes: 3
    steps:
      - uses: styfle/cancel-workflow-action@0.10.0
        with:
          workflow_id: nodejs.yml
          access_token: ${{ github.token }}
